version: '3.9'

services:
    node:
        tty: true
        image: 'fabiosereno/app-next-blogg:1.4.0'
        ports:
            - '3000:3000'
        volumes:
            - './project:/usr/src/app/'
    mongo:
      image: mongo:5.0.3
      restart: always
      volumes:
        - mongo-db:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password1
    mongo-express:
      image: mongo-express:0.54.0
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: password1
        ME_CONFIG_MONGODB_SERVER: app_nextblog_mongo_1
        ME_CONFIG_MONGODB_PORT: 27017

volumes:
  mongo-db: