version: '3.9'

services:
    node:
        tty: true
        image: 'fabiosereno/app-next-blogg:1.4.0'
        ports:
            - '3000:3000'
        volumes:
            - './project:/usr/src/app/'