version: '3.9'

services:
    server:
        tty: true
        image: 'fabiosereno/app-next-blogg:1.1.0'
        ports:
            - '3000:3000'
        volumes:
            - './blogg:/usr/src/app/'